Simpler handling surrogate pairs
dmonad/lib0 pull request #46
Opened 2022-10-25 00:39 UTC by KentoMoriwaki

Simpler and more performant impl of https://github.com/dmonad/lib0/pull/45

2023-03-16 08:48 UTC, Young6118 commented
Good job!

2023-03-16 15:33 UTC, dmonad requested changes
I think I like this solution. Can you please adjust it a bit so we don't have to perform many unnecessary checks? 

Ideally, we can only perform the check once at the end of the function. There should be a small comment that describes the issue that the surrogate checks solve (i.e. refer to the ticket)

2023-03-16 15:33 UTC, dmonad commented on diff.js
> +    inSurrogate = highSurrogateRegex.test(a[left])
Is it necessary to test this in every iteration? Couldn't we perform all the checks at the very end of the function and then adjust `left` & `right` if necessary?

2023-03-17 04:35 UTC, KentoMoriwaki commented
@dmonad I fixed and updated specs to improve coverages.

2023-03-17 11:57 UTC, dmonad approved these changes
Thank you, this looks great!

I'm going to publish a new release today.

2023-03-17 11:58 UTC, merged

2023-03-19 13:57 UTC, tommoor commented
The link in the original PR suggests that this would fix https://github.com/yjs/yjs/issues/303 however the behavior doesn't seem to have changed in regards to those original reproduction instructions.

2023-03-20 04:46 UTC, KentoMoriwaki commented
@tommoor  Are you certain you're using `lib0@0.2.69` in your environment? I have verified that this issue has been resolved in mine.